version: '3.1'

services:
  mysql:
    container_name: 'mysql-image'
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=freelance_flow
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
    ports:
      - '65050:3306'

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - '8808:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/freelance_flow
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345678

volumes:
  pg_freelance_flow:
